=== IsabelMont/lm-xml-dtds/02_ejercicios/02_agenda/agenda.dtd
<!ELEMENT agenda (contacto*)>
        <!ELEMENT contacto (nombre, direccion, ciudad, provincia,codigopostal,numeros,email,web,compañia)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT ciudad (#PCDATA)>
        <!ELEMENT provincia (#PCDATA)>
        <!ELEMENT codigopostal (#PCDATA)>
        <!ELEMENT numeros (telefono, fax)>
        <!ELEMENT telefono (#PCDATA)>
        <!ELEMENT fax (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT web (#PCDATA)>
        <!ELEMENT compañia (#PCDATA)>

=== IsabelMont/lm-xml-dtds/02_ejercicios/02_agenda/agenda.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <contacto>
        <nombre>Carlos</nombre>
        <direccion>calle asturias</direccion>
        <ciudad>Asturias</ciudad>
        <provincia>Asturias</provincia>
        <codigopostal>01001</codigopostal>
        <numeros>
            <telefono>945152255</telefono>
            <fax>945222222</fax>
        </numeros>
        <email>carlos@carlos.com</email>
        <web>www.noteconocenadie.com</web>
        <compañia>Carlos.ck</compañia>
    </contacto>
</agenda>
